import arcade

# Constants
SCREEN_TITLE = "Lander Arcade"
SCALING = 1.0
WORLD_WIDTH = 20000
WORLD_HEIGHT = 2500
SPACE_END = int((5 / 6) * WORLD_HEIGHT)
SPACE_START = int((2/3) * WORLD_HEIGHT)
BACKGROUND_COLOR = arcade.color.BLACK
